-- מחיקת טבלאות שתלויות באחרות קודם
DROP TABLE IF EXISTS RoundResult CASCADE;
DROP TABLE IF EXISTS Round CASCADE;
DROP TABLE IF EXISTS Registration CASCADE;
DROP TABLE IF EXISTS Tournament CASCADE;

DROP TABLE IF EXISTS Move CASCADE;
DROP TABLE IF EXISTS Game CASCADE;
DROP TABLE IF EXISTS GameVariant CASCADE;
DROP TABLE IF EXISTS TimeControl CASCADE;

-- מחיקת טבלאות העזר
DROP TABLE IF EXISTS Club CASCADE;
DROP TABLE IF EXISTS Player CASCADE;